### ISSUE TITLE
nullable field

### ISSUE THREAD

**Issue by cyrilchapon** [RideAmigosCorp/mongoose-geojson-schema#20]
When updating a document with a mongoose geojson schema, and trying to set it to null, when `required: false`, I'm getting :

```
error:  TypeError: Cannot read property 'type' of null
    at SchemaType.Polygon.cast (C:\Users\Cyril\Code\imagine-network-api\node_modules\mongoose-geojson-schema\index.js:27
5:15)
    at SchemaType.castForQuery (C:\Users\Cyril\Code\imagine-network-api\node_modules\mongoose\lib\schematype.js:952:15)
    at castUpdateVal (C:\Users\Cyril\Code\imagine-network-api\node_modules\mongoose\lib\services\query\castUpdate.js:288
:17)
    at walkUpdatePath (C:\Users\Cyril\Code\imagine-network-api\node_modules\mongoose\lib\services\query\castUpdate.js:20
9:20)
    at castUpdate (C:\Users\Cyril\Code\imagine-network-api\node_modules\mongoose\lib\services\query\castUpdate.js:70:18)
    at Query._castUpdate (C:\Users\Cyril\Code\imagine-network-api\node_modules\mongoose\lib\query.js:2804:10)
    at castDoc (C:\Users\Cyril\Code\imagine-network-api\node_modules\mongoose\lib\query.js:2830:18)
    at Query._findAndModify (C:\Users\Cyril\Code\imagine-network-api\node_modules\mongoose\lib\query.js:2000:17)
    at Query._findOneAndUpdate (C:\Users\Cyril\Code\imagine-network-api\node_modules\mongoose\lib\query.js:1856:8)
    at C:\Users\Cyril\Code\imagine-network-api\node_modules\kareem\index.js:253:8
    at C:\Users\Cyril\Code\imagine-network-api\node_modules\kareem\index.js:18:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by joshkopecek** [comment]
I believe the preferred approach would be deleting the property from the containing object rather than setting it as null. If it's null it'll think there's an object to be cast/validated.

**Comment by cyrilchapon** [comment]
> I believe the preferred approach would be deleting the property from the containing object rather than setting it as null. If it's null it'll think there's an object to be cast/validated.

Well that works, but an `$unset` field doesn't mean the same as a `null` field.
`null` is for deliberate absence of value, *not set* rather means not-really-wanted absence of value.

**Comment by joshkopecek** [comment]
If you cast null as an empty GeoJSON object then it's going to want coordinate values, and if those are empty any geospatial index you have on Mongo will fail AFAIK. If the property doesn't exist it will simply be absented from the index.

**Comment by cyrilchapon** [comment]
> any geospatial index you have on Mongo will fail AFAIK

Actually they are [sparse by default](https://docs.mongodb.com/manual/core/2dsphere/#sparse-property), and null is ok with sparse indexes.

**Comment by joshkopecek** [comment]
Ok I'll need to check and write a test for this. Thanks for bringing it to my attention. Obviously my knowledge of the Mongo API is a bit rusty!

**Comment by joshkopecek** [comment]
@cyrilchapon I know this is late, but could you give me an example of the schema and data that you were working with? It would be nice to get this working properly with systems requiring sparse indexes.

**Comment by joshkopecek** [comment]
Closing as seriously stale.
