### ISSUE TITLE
Polygon, Geometry and Feature get the following error

### ISSUE THREAD

**Issue by heatmonkey** [RideAmigosCorp/mongoose-geojson-schema#3]
..\data\node_modules\mongoose\lib\schema\array.js:58
    this.caster = new caster(null, castOptions);
                  ^
TypeError: string is not a function
    at new SchemaArray (\data\node_modules\mongoose\lib\schema\array.js:58:19)
    at Function.Schema.interpretAsType (..\data\node_modules\mongoose\lib\schema.js:350:12)
    at Schema.path (..\data\node_modules\mongoose\lib\schema.js:305:29)
    at Schema.add (..\data\node_modules\mongoose\lib\schema.js:217:12)
    at Schema.add (..\data\node_modules\mongoose\lib\schema.js:212:14)
    at new Schema (..\data\node_modules\mongoose\lib\schema.js:73:10)
    at Mongoose.Schema (..\data\node_modules\mongoose\lib\schema.js:53:12)
    at Object.<anonymous>

**Comment by mmacmillan** [comment]
@markstos mongoose 4.0.3, mongodb 2.6.9...still experiencing this issue.  The fix to allow validation would to use the Schema.Types from mongoose, which would require adding that dependency.  Without, we have to use an empty array, which falls back on a Mixed type.  Will you accept a pull request that essentially does what @heatmonkey proposed, or do you have another fix for this issue?

**Comment by markstos** [comment]
@mmacmillan I don't mind adding a dependency, if we can fix this and still have validation.  

I don't have an alternate fix for this.

**Comment by markstos** [comment]
This should be fixed by the 1.0.0 release, thanks to @joshkopecek 

Notice the syntax is slightly different, so it's not a drop-in upgrade. 

Re-open if you still see an issue with the 1.0 release.
